---
# This docker-compose file will start some containers that act like VMs in a VPC
x-base-image: &baseimage
  image: my-geerlingguy-docker-ubuntu-ansible:latest
  build: .
services:
  zk1:
    <<: *baseimage
    hostname: zk1
    container_name: zk1 
    ports:
     - "2181:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  zk2:
    <<: *baseimage
    hostname: zk2
    container_name: zk2
    ports:
     - "2182:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  zk3:
    <<: *baseimage
    hostname: zk3
    container_name: zk3
    ports:
     - "2183:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka1:
    <<: *baseimage
    hostname: kafka1
    container_name: kafka1
    ports:
     - "9092:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc1:
    <<: *baseimage
    hostname: kc1
    container_name: kc1 
    ports:
     - "9093:9093"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc2:
    <<: *baseimage
    hostname: kc2
    container_name: kc2 
    ports:
     - "9094:9093"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc3:
    <<: *baseimage
    hostname: kc3
    container_name: kc3 
    ports:
     - "9095:9093"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host

# We use this container to execute all ansible playbooks
  ansible:
    <<: *baseimage
    hostname: ansible
    container_name: ansible
    command: "/usr/bin/bash -c \"sleep infinity\""
    volumes:
      #- ./cp-ansible:/etc/ansible:rw
      - ./hosts.yml:/etc/ansible/hosts.yml:rw
      - ./ansible.cfg:/etc/ansible/ansible.cfg:rw
      # Required as ansible will use docker to control the other nodes
      - /var/run/docker.sock:/var/run/docker.sock:rw
