---
# This docker-compose file will start some containers that act like VMs in a VPC
services:
  zk1:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: zk1
    container_name: zk1 
    ports:
     - "2181:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  zk2:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: zk2
    container_name: zk2
    ports:
     - "2182:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  zk3:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: zk3
    container_name: zk3
    ports:
     - "2183:2181"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kafka1:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kafka1
    container_name: kafka1
    ports:
     - "9092:9092"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc1:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kc1
    container_name: kc1 
    ports:
     - "9093:9093"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc2:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kc2
    container_name: kc2 
    ports:
     - "9094:9093"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host
  kc3:
    image: my-geerlingguy-docker-ubuntu-ansible:latest
    hostname: kc3
    container_name: kc3 
    ports:
     - "9095:9093"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup: host